<?php

namespace App\Filament\Resources\Documents\Pages;

use App\Filament\Resources\Documents\DocumentResource;
use App\Models\Document;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class CreateDocument extends CreateRecord
{
    protected static string $resource = DocumentResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $params = [
            'size' => Storage::disk('s3')->size($data['path']),
            'type' => Storage::disk('s3')->mimeType($data['path']),
        ];
        $data['size'] = $params['size'];
        $data['mime'] = $params['type'];
        $data['user_id'] = auth()->id();
        $data['reference'] = Document::generateReference();
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
